### ISSUE TITLE
Homey -> Verisure App Lock out.

### ISSUE THREAD

**Issue by PeterEde78** [Charlie-Root/homey-nl-verisure#34] opened 2018-09-25 13:59 UTC
hi i have a problem that i get lock out from the Iphone Verisure APP as Homey is make lots of requests.
i spoken to verisure. is it possible to make homey to ask less request from the verisure server ?
a settings for that ?
/Peter (sweden)

**Comment by Charlie-Root** [comment] 2018-09-25 14:10
Duplicate of #32

**Closed by Charlie-Root** 2018-09-25 14:10 UTC
Labels: duplicate
